"""empty message

Revision ID: 77022c811670
Revises: e1025544bc50
Create Date: 2020-06-13 14:44:29.275071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77022c811670'
down_revision = 'e1025544bc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('field', sa.String(length=256), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultant')
    # ### end Alembic commands ###
